name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.12
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CUSTOM_DOMAIN: www.redhatspain.com

